name: "CI"

on:
  pull_request:
  push:
    branches:
    - '*'
    tags:
    - 'v*'

jobs:
  docker:
    uses: na4ma4/actions/.github/workflows/makefiles-docker.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      docker-push: ${{ startsWith(github.ref, 'refs/tags/v') }}
